### ISSUE TITLE
Time display of first action

### ISSUE THREAD

**Issue by levinablution** [236571208/IdeaColler#1]
1.在录制操作时，第一个动作的时间点状态显示为0.0，不知是否会引起用户误解（数据库中表现是正确的）

**Comment by 236571208** [comment]
不是以第一个动作的时间作为起始时间么，所以相对时间肯定是0了，有什么建议吗？

**Comment by levinablution** [comment]
有两个问题之前提到过了：
1.以前的注册功能用不了了，初步判断是添加了一个email输入栏的问题
2.录制时每次点击屏幕，需要屏幕闪动一下，以便用户判断已经点击过了，这个在ios的app上实现了，svn里有下载

还有几个问题需要解决：
1.“待录制”界面作如下修改，支持多次录制相同过程名
![screenshot_2015-05-22-10-27-17](https://cloud.githubusercontent.com/assets/10678669/7763523/76fc3132-0074-11e5-9bab-6c133a43519f.png)

![screenshot_2015-05-22-10-35-00](https://cloud.githubusercontent.com/assets/10678669/7763537/b3878890-0074-11e5-9672-99578ad56ea3.png)

2.“已录制”界面作如下修改，支持显示相同的过程名

![screenshot_2015-05-22-10-47-07](https://cloud.githubusercontent.com/assets/10678669/7763553/1edc90cc-0075-11e5-8149-6f5a55c32d25.png)

3.apk安装包名字调整为"IEToolKit.apk"，桌面应用名调整为"IE工具包"，相应的logo也作更改，这些我改好了，你确认一下就行了，源码还在之前的svn目录。
